name: Default reconstruction system config
fragment_size: 100
device: CUDA:1
engine: tensor
multiprocessing: false
path_dataset: 'replica'
depth_folder: depth
color_folder: color
path_intrinsic: 'replica/camera_intrinsic.json'
path_color_intrinsic: ''
depth_min: 0.0
depth_max: 20.0
depth_scale: 6553.5
odometry_method: hybrid
odometry_loop_interval: 10
odometry_loop_weight: 0.1
odometry_distance_thr: 0.07
icp_method: colored
icp_voxelsize: 0.05
icp_distance_thr: 0.07
global_registration_method: ransac
registration_loop_weight: 0.1
integrate_color: true
voxel_size: 0.05
trunc_voxel_multiplier: 8.0
block_count: 4000
est_point_count: 8000000
surface_weight_thr: 3.0
